spring.application.name=studentManagement
# DataSource configuration
server.tomcat.accesslog.enabled
spring.datasource.url=jdbc:postgresql://dpg-coafrhkf7o1s73dpe8eg-a.oregon-postgres.render.com/database_l01m
spring.datasource.username=database_l01m_user
spring.datasource.password=27HDC9QMnrybzobo54LALx3fUHvEJ6kX

# Hibernate configuration
spring.jpa.properties.hibernate.format-sql=true
spring.jpa.hibernate.ddl-auto=update 
spring.jpa.show-sql=true

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp


# Allow all origins
spring.webflux.cors.allowed-origins=*
